/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ContractDAO;
import model.ContractDTO;
import model.PublisherDAO;

/**
 *
 * @author yj
 */
public class ContractAdd extends javax.swing.JFrame implements ActionListener{
    SimpleDateFormat fm = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
    private PublisherDAO publisherDao;
    private ContractDAO contractDao;
    private Publication publication;

    /**
     * Creates new form BookAddEdit
     */

    public ContractAdd() {
        super("계약 등록");
        initComponents();

        init();
        addEvent();
    }
    
    public ContractAdd(Publication publication) {
        this();
        this.publication = publication;
    }
    
    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        contractDao = new ContractDAO();
        publisherDao = new PublisherDAO();
        setLocationRelativeTo(null); //가운데 배치
        

        Date date = new Date();
        String year = (date.getYear() + 1900) + "";
        String month = (date.getMonth() + 1) + "";
        String day = date.getDate() + "";
        String hour = date.getHours() + "";
        String minute = date.getMinutes() + "";
        String second = date.getSeconds() + "";

        tf_year.setText(year);
        tf_month.setText(month);
        tf_day.setText(day);
        tf_hour.setText(hour);
        tf_minute.setText(minute);
        tf_second.setText(second);
        bt_ok.enable(false);
        tf_year.enable(false);
        tf_month.enable(false);
        tf_day.enable(false);
        tf_conNo.enable(false);
        tf_hour.setVisible(false);
        tf_minute.setVisible(false);
        tf_second.setVisible(false);
        
        try {
            puNameComboBoxSet();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }        


    }

    private void addEvent() {
         bt_conNo.addActionListener(this);
        bt_nameCheck.addActionListener(this);
        bt_ok.addActionListener(this);
        bt_cancel.addActionListener(this);    
    }
    
    
    //---------------이벤트 핸들러-------------------------------------------------------

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            if (e.getSource() == bt_conNo) {
                conNoGet();
            } else if (e.getSource() == bt_nameCheck) {
                empNameCheck();
            } else if (e.getSource() == bt_ok) {
                try {
                    contractAdd();
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }
            } else if (e.getSource() == bt_cancel) {
                this.dispose();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_puNo = new javax.swing.JLabel();
        lb_puName = new javax.swing.JLabel();
        lb_puTel = new javax.swing.JLabel();
        bt_ok = new javax.swing.JButton();
        tf_conNo = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        cb_puName = new javax.swing.JComboBox<>();
        lb_bookNo = new javax.swing.JLabel();
        tf_year = new javax.swing.JTextField();
        tf_day = new javax.swing.JTextField();
        tf_month = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_cancel = new javax.swing.JButton();
        bt_conNo = new javax.swing.JButton();
        bt_nameCheck = new javax.swing.JButton();
        tf_second = new javax.swing.JTextField();
        tf_minute = new javax.swing.JTextField();
        tf_hour = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_puNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puNo.setText("계약번호");

        lb_puName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puName.setText("담당자");

        lb_puTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puTel.setText("거래처");

        bt_ok.setText("확인");

        cb_puName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_puNameActionPerformed(evt);
            }
        });

        lb_bookNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bookNo.setText("계약일");

        tf_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dayActionPerformed(evt);
            }
        });

        jLabel2.setText("년");

        jLabel3.setText("월");

        jLabel4.setText("일");

        bt_cancel.setText("취소");

        bt_conNo.setText("조회");

        bt_nameCheck.setText("확인");

        tf_second.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_secondActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_puTel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_puName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_bookNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_year, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_month, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_day, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_puNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lb_puName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_conNo, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(tf_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_conNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_nameCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_hour, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tf_minute, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tf_second, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_bookNo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_puNo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_conNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_conNo)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puName)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_nameCheck))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puTel)
                    .addComponent(cb_puName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ok)
                    .addComponent(bt_cancel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_second, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_minute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dayActionPerformed

    private void cb_puNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_puNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_puNameActionPerformed

    private void tf_secondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_secondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_secondActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookAddEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookAddEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookAddEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookAddEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookAddEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_conNo;
    private javax.swing.JButton bt_nameCheck;
    private javax.swing.JButton bt_ok;
    private javax.swing.JComboBox<String> cb_puName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_bookNo;
    private javax.swing.JLabel lb_puName;
    private javax.swing.JLabel lb_puNo;
    private javax.swing.JLabel lb_puTel;
    private javax.swing.JTextField tf_conNo;
    private javax.swing.JTextField tf_day;
    private javax.swing.JTextField tf_hour;
    private javax.swing.JTextField tf_minute;
    private javax.swing.JTextField tf_month;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_second;
    private javax.swing.JTextField tf_year;
    // End of variables declaration//GEN-END:variables

   //사원이름 존재유무 체크
    private void empNameCheck() throws SQLException {
        String empName = tf_name.getText();
        int emp = contractDao.empNameCheck(empName);

        if (emp > 0) {
            JOptionPane.showMessageDialog(this, "존재하는 사원명입니다");
            bt_ok.enable(true);
        } else {
            JOptionPane.showMessageDialog(this, "존재하지 않는 사원명입니다.");
            tf_name.requestFocus();
            tf_name.setText("");
        }
    }

    //계약추가
    private void contractAdd() throws SQLException, ParseException {
        String inNo = tf_conNo.getText();
        String year = tf_year.getText();
        String month = tf_month.getText();
        String day = tf_day.getText();
        String hour = tf_hour.getText();
        String minute = tf_minute.getText();
        String second = tf_second.getText();
        Timestamp regdate = Timestamp.valueOf(year + "-" + month + "-" + day + " " + hour + ":" + minute + ":" + second);
        String empName = tf_name.getText();
        String conNo = conNoGet();
        String puName = (String) cb_puName.getSelectedItem();

        //유효성검사
        if (empName == null || empName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "담당자를 입력해주세요");
            tf_name.requestFocus();
            return;
        } else if (conNo == null || conNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "계약번호를 입력하세요");
        }
        System.out.println("계약일" + regdate);
        //2
        ContractDTO dto = new ContractDTO(conNo, regdate, contractDao.empNo_search(empName), publisherDao.publisherPuId(puName));
        int result = contractDao.contractAdd(dto);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "계약등록이 완료되었습니다.");
            publication.contractShowAll("");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "계약등록 실패.");
            return;
        }
    }
    
    //출판사 콤보박스 세팅
    private void puNameComboBoxSet() throws SQLException {
        Vector<String> vec = publisherDao.publisherComboBoxSet();
        
        DefaultComboBoxModel<String> puNameComboBoxModel = new DefaultComboBoxModel<>(vec);
        cb_puName.setModel(puNameComboBoxModel);
    }
    
    private String conNoGet() throws SQLException {
        String conNo = contractDao.conNoAdd();
        tf_conNo.setText(conNo);
        
        return conNo;
    }


}
