/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ContractDAO;
import model.ContractDTO;
import model.PublisherDAO;

/**
 *
 * @author yj
 */
public class ContractEdit extends javax.swing.JFrame implements ActionListener{
    SimpleDateFormat fm = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
    private PublisherDAO publisherDao;
    private ContractDAO contractDao;
    private String conNo;
    private Publication publication;
    /**
     * Creates new form ContractEdit
     */
    public ContractEdit() {
        super("계약 등록");
        initComponents();

        init();
        addEvent();
        setLocationRelativeTo(null); //가운데 배치
    }
    
    public ContractEdit(String conNo, Publication publication) {
        this();
        tf_conNo.setText(conNo);
        this.publication = publication;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_puName = new javax.swing.JLabel();
        lb_puHp = new javax.swing.JLabel();
        bt_ok = new javax.swing.JButton();
        tf_name = new javax.swing.JTextField();
        bt_cancel = new javax.swing.JButton();
        lb_bookNo = new javax.swing.JLabel();
        tf_conNo = new javax.swing.JTextField();
        bt_nameCheck = new javax.swing.JButton();
        cb_puName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_puName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puName.setText("담당자");

        lb_puHp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puHp.setText("거래처");

        bt_ok.setText("수정");

        bt_cancel.setText("취소");

        lb_bookNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_bookNo.setText("계약번호");

        bt_nameCheck.setText("검색");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_puHp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cb_puName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_bookNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_conNo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_puName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_nameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_bookNo)
                    .addComponent(tf_conNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puName)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_nameCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puHp)
                    .addComponent(cb_puName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ok)
                    .addComponent(bt_cancel))
                .addGap(159, 159, 159))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContractEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContractEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContractEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContractEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContractEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_nameCheck;
    private javax.swing.JButton bt_ok;
    private javax.swing.JComboBox<String> cb_puName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_bookNo;
    private javax.swing.JLabel lb_puHp;
    private javax.swing.JLabel lb_puName;
    private javax.swing.JTextField tf_conNo;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        contractDao = new ContractDAO();
        publisherDao = new PublisherDAO();

        tf_conNo.setText(conNo);
        tf_conNo.enable(false);

        try {
            puNameComboBoxSet();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addEvent() {
        bt_nameCheck.addActionListener(this);
        bt_ok.addActionListener(this);
        bt_cancel.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        try {
            if (e.getSource() == bt_nameCheck) {
                empNameCheck();
            } else if (e.getSource() == bt_ok) {
                contractEdit();
            } else if (e.getSource() == bt_cancel) {
                this.dispose();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    //계약수정
    private void contractEdit() throws SQLException {
        String conNo = tf_conNo.getText();
        String name = tf_name.getText();
        String empNo = contractDao.empNo_search(name);
        String puName = (String) cb_puName.getSelectedItem();
        String puId = publisherDao.publisherPuId(puName);

        ContractDTO dto = new ContractDTO();

        dto.setConNo(conNo);
        dto.setEmpNo(empNo);
        dto.setPuId(puId);

        if (name == null || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "사원이름을 입력해주세요");
            tf_name.requestFocus();
            return;
        }
        if (cb_puName.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "출판사를 선택해 주세요");
            return;
        }

        int cnt = contractDao.contractEdit(dto);
        
        if(cnt > 0) {
            JOptionPane.showMessageDialog(this, "수정성공");
            publication.contractShowAll("");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "수정실패");
        }
    }

    //사원이름 존재유무 체크
    private void empNameCheck() throws SQLException {
        String empName = tf_name.getText();
        int emp = contractDao.empNameCheck(empName);

        if (emp > 0) {
            JOptionPane.showMessageDialog(this, "존재하는 사원명입니다");
            bt_ok.enable(true);
        } else {
            JOptionPane.showMessageDialog(this, "존재하지 않는 사원명입니다.");
            tf_name.requestFocus();
            tf_name.setText("");
        }
    }

    //출판사 콤보박스 세팅
    private void puNameComboBoxSet() throws SQLException {
        Vector<String> vec = publisherDao.publisherComboBoxSet();

        DefaultComboBoxModel<String> puNameComboBoxModel = new DefaultComboBoxModel<>(vec);
        cb_puName.setModel(puNameComboBoxModel);
    }

    private String conNoGet() throws SQLException {
        String conNo = contractDao.conNoAdd();
        tf_conNo.setText(conNo);

        return conNo;
    }
}
