/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.EmpDAO;
import model.EmpDTO;
import model.InOrderDAO;
import model.InOrderDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.InOrderTableDTO;
import model.StockDAO;

/**
 *
 * @author YJ
 */
public class InOrderEditGUI extends javax.swing.JFrame implements ActionListener{
    private InOrderDAO Dao;
    private String inNo;
    

    /**
     * Creates new form InOrderFormGUI
     */
    public InOrderEditGUI() {
        super("상품 입고 수정");
        initComponents();
        
        init();
        addEvent();
    }
    
    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dao = new InOrderDAO();
        setLocationRelativeTo(null); //가운데 배치
    }//init
    

    InOrderEditGUI(String inNo) {
        this();
        this.inNo=inNo;
        
        try {
            showInOrder();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }        
    }



    private void addEvent() {
       bt_add.addActionListener(this);
       tf_qty.addKeyListener(new EventHandler());
       tf_cost.addKeyListener(new EventHandler());
    }//addEvent


    
//======================================이벤트 핸들러=====================================================
    @Override
    public void actionPerformed(ActionEvent e) {
     if(e.getSource()==bt_add){
         try {
             EditInOrder();
         } catch (SQLException ex) {
             ex.printStackTrace();
         }
     }
    }//actionPerformed
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jp_InNo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_inNo = new javax.swing.JTextField();
        jp_InNo1 = new javax.swing.JPanel();
        lb_conNo = new javax.swing.JLabel();
        tf_conNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hp_conDate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_year = new javax.swing.JTextField();
        tf_month = new javax.swing.JTextField();
        tf_day = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jp_empName = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_empName = new javax.swing.JTextField();
        jp_qty = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_qty = new javax.swing.JTextField();
        jp_price = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_cost = new javax.swing.JTextField();
        bt_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("입고 수정");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("입고번호");

        tf_inNo.setEditable(false);
        tf_inNo.setEnabled(false);
        tf_inNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_inNoActionPerformed(evt);
            }
        });

        lb_conNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_conNo.setText("계약번호");

        tf_conNo.setEditable(false);
        tf_conNo.setEnabled(false);
        tf_conNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_conNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_InNo1Layout = new javax.swing.GroupLayout(jp_InNo1);
        jp_InNo1.setLayout(jp_InNo1Layout);
        jp_InNo1Layout.setHorizontalGroup(
            jp_InNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_InNo1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lb_conNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_conNo, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
        );
        jp_InNo1Layout.setVerticalGroup(
            jp_InNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_InNo1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jp_InNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_conNo)
                    .addComponent(tf_conNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_InNoLayout = new javax.swing.GroupLayout(jp_InNo);
        jp_InNo.setLayout(jp_InNoLayout);
        jp_InNoLayout.setHorizontalGroup(
            jp_InNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_InNoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jp_InNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_InNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_InNoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_inNo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_InNoLayout.setVerticalGroup(
            jp_InNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_InNoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_InNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_inNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jp_InNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("상품 입고 수정");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("입고일");

        tf_year.setEditable(false);
        tf_year.setEnabled(false);

        tf_month.setEditable(false);
        tf_month.setEnabled(false);

        tf_day.setEditable(false);
        tf_day.setEnabled(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("년");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("월");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("일");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("담당자");

        tf_empName.setEditable(false);
        tf_empName.setEnabled(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("수량");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("수량단가");

        javax.swing.GroupLayout jp_priceLayout = new javax.swing.GroupLayout(jp_price);
        jp_price.setLayout(jp_priceLayout);
        jp_priceLayout.setHorizontalGroup(
            jp_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_priceLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jp_priceLayout.setVerticalGroup(
            jp_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_priceLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jp_priceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_qtyLayout = new javax.swing.GroupLayout(jp_qty);
        jp_qty.setLayout(jp_qtyLayout);
        jp_qtyLayout.setHorizontalGroup(
            jp_qtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_qtyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_qtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_qtyLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_qtyLayout.setVerticalGroup(
            jp_qtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_qtyLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jp_qtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_add.setText("등록");

        javax.swing.GroupLayout jp_empNameLayout = new javax.swing.GroupLayout(jp_empName);
        jp_empName.setLayout(jp_empNameLayout);
        jp_empNameLayout.setHorizontalGroup(
            jp_empNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_empNameLayout.createSequentialGroup()
                .addGroup(jp_empNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_empNameLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_empName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jp_qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jp_empNameLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_empNameLayout.setVerticalGroup(
            jp_empNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_empNameLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jp_empNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout hp_conDateLayout = new javax.swing.GroupLayout(hp_conDate);
        hp_conDate.setLayout(hp_conDateLayout);
        hp_conDateLayout.setHorizontalGroup(
            hp_conDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hp_conDateLayout.createSequentialGroup()
                .addGroup(hp_conDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hp_conDateLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_year, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_month, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_day, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hp_conDateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jp_empName, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        hp_conDateLayout.setVerticalGroup(
            hp_conDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hp_conDateLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(hp_conDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hp_conDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_InNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jp_InNo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hp_conDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_inNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_inNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_inNoActionPerformed

    private void tf_conNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_conNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_conNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InOrderEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InOrderEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InOrderEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InOrderEditGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InOrderEditGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JPanel hp_conDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jp_InNo;
    private javax.swing.JPanel jp_InNo1;
    private javax.swing.JPanel jp_empName;
    private javax.swing.JPanel jp_price;
    private javax.swing.JPanel jp_qty;
    private javax.swing.JLabel lb_conNo;
    private javax.swing.JTextField tf_conNo;
    private javax.swing.JTextField tf_cost;
    private javax.swing.JTextField tf_day;
    private javax.swing.JTextField tf_empName;
    private javax.swing.JTextField tf_inNo;
    private javax.swing.JTextField tf_month;
    private javax.swing.JTextField tf_qty;
    private javax.swing.JTextField tf_year;
    // End of variables declaration//GEN-END:variables

//======================================키보드 유효성 검사=====================================================
    //입고 등록시 수량, 가격에 숫자 이외의 입력 방지
    //숫자 이외 입력이 발생하면(backSpace 제외)
    class EventHandler extends KeyAdapter{
        @Override
        public void keyPressed(KeyEvent e) {
            JTextField j = (JTextField)e.getSource();
            
            if(e.getSource()==tf_qty ||  e.getSource()==tf_cost){
                if(!(e.getKeyChar()>='0'&&e.getKeyChar()<='9'||e.getKeyCode()==8)){
                    insertNumberType(j);
                }
            }
        }
    }
    //숫자 이외 입력 방지
    private void insertNumberType(JTextField tf) {
            JOptionPane.showMessageDialog(this, "숫자만 입력 가능합니다.");
            tf.requestFocus();
            tf.setText("");
            return;
    }    
//======================================키보드 유효성 검사=====================================================   

    
    //수정을 위한 입고 정보 출력
    private void showInOrder() throws SQLException {
        //1
        
        //2
        InOrderTableDTO dto = Dao.serchInOrderEdit(inNo);

        
        //3
        Timestamp inDate =  dto.getInDate();
        int year = inDate.getYear();
        int month = inDate.getMonth();
        int day = inDate.getDay();
        
                
        tf_inNo.setText(dto.getInNo());
        tf_conNo.setText(dto.getConNo());
        tf_year.setText(year+"");
        tf_month.setText(month+"");
        tf_day.setText(day+"");
        tf_empName.setText(dto.getEmpName());
        tf_qty.setText(dto.getQty()+"");
        tf_cost.setText(dto.getCost()+"");

    }    
    
    
    //입고 수정
    private void EditInOrder() throws SQLException {
        
        //1.
        String qty = tf_qty.getText();
        String cost = tf_cost.getText();
        
        //유효성 검사
        if(qty==null||qty.isEmpty()){
            JOptionPane.showConfirmDialog(this, "수량을 입력해주세요");
            tf_qty.requestFocus();
            return;
        }else if(cost==null && cost.isEmpty()){
            JOptionPane.showMessageDialog(this, "금액을 입력해주세요");
            tf_cost.requestFocus();
            return;
        }
        
        //2.
        //재고수량<수정값 일 경우 수정 막기 
        //총 재고량 <(기존수량-수정수량)
        //트리거 실행 오류 방지, -값 입력 방지
        String conNo = tf_conNo.getText();
        int inOrderQty = Dao.selectQty(conNo, Integer.parseInt(qty));
        StockDAO stockDao = new StockDAO();
        boolean check = stockDao.checkStock(conNo, inOrderQty);
        
        
        if(check){
            InOrderDTO dto = new InOrderDTO(inNo, Integer.parseInt(qty), Integer.parseInt(cost));
            int result = Dao.updateInOrder(dto);



            //3.
            if(result>0){
                JOptionPane.showMessageDialog(this, "수정이 완료되었습니다.");
                InOrderEditGUI.this.dispose();
                InOrderGUI f= new InOrderGUI();


            }else{
                JOptionPane.showMessageDialog(this, "수정에 실패하였습니다. 다시 시도해주세요.");
                return;
            }
        }else{
            JOptionPane.showMessageDialog(this, "현재 재고보다 작은 값으로는 수정할 수 없습니다.");
            return;
        }

        
    }

}
