/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.PublisherDAO;
import model.PublisherDTO;

/**
 *
 * @author yj
 */
public class PublisherEdit extends javax.swing.JFrame implements ActionListener{
    private PublisherDAO Dao;
    private String puId;
    private String puName;
    
    private String[] colNames = {"번호", "출판사명", "회사번호", "담당자명", "담당자 연락처"};
    
    /**
     * Creates new form PublisherEdit
     */
    public PublisherEdit(String puId) {
        initComponents();
        PublisherDTO Dto;
        
        this.puId = puId;
        init();
        addEvent();
    }

    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        tf_puId.enable(false);
        tf_puName.enable(false);
        bt_Dup.enable(false);
        Dao = new PublisherDAO();
        setTitle("출판사 수정");
        setLocationRelativeTo(null); //가운데 배치
        try {
            showPublisher();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//init

    private void addEvent() {
        bt_Dup.addActionListener(this);
        bt_add.addActionListener(this);
        
        tf_puTel.addActionListener(this);
        tf_puManager.addActionListener(this);
        tf_puHp.addActionListener(this);
    }

    
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == bt_add) {
            try {
                Editpublisher();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_puNo = new javax.swing.JLabel();
        lb_puName = new javax.swing.JLabel();
        lb_puTel = new javax.swing.JLabel();
        lb_puManager = new javax.swing.JLabel();
        lb_puHp = new javax.swing.JLabel();
        bt_add = new javax.swing.JButton();
        tf_puId = new javax.swing.JTextField();
        tf_puManager = new javax.swing.JTextField();
        tf_puHp = new javax.swing.JTextField();
        bt_Dup = new javax.swing.JButton();
        tf_puName = new javax.swing.JTextField();
        tf_puTel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_puNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puNo.setText("사업자 등록번호");

        lb_puName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puName.setText("출판사명");

        lb_puTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puTel.setText("회사대표번호");

        lb_puManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puManager.setText("담당자명");

        lb_puHp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_puHp.setText("담당자연락처");

        bt_add.setText("등록");

        bt_Dup.setText("검색");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_puNo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lb_puName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_puId, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Dup))
                            .addComponent(tf_puName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_puHp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_puHp))
                    .addComponent(bt_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_puTel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lb_puManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_puManager)
                            .addComponent(tf_puTel))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_puNo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_puId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_Dup)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puName)
                    .addComponent(tf_puName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puTel)
                    .addComponent(tf_puTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puManager)
                    .addComponent(tf_puManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_puHp)
                    .addComponent(tf_puHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PublisherEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PublisherEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PublisherEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PublisherEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Dup;
    private javax.swing.JButton bt_add;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_puHp;
    private javax.swing.JLabel lb_puManager;
    private javax.swing.JLabel lb_puName;
    private javax.swing.JLabel lb_puNo;
    private javax.swing.JLabel lb_puTel;
    private javax.swing.JTextField tf_puHp;
    private javax.swing.JTextField tf_puId;
    private javax.swing.JTextField tf_puManager;
    private javax.swing.JTextField tf_puName;
    private javax.swing.JTextField tf_puTel;
    // End of variables declaration//GEN-END:variables

    //수정
    private void Editpublisher() throws SQLException {

        //1 사용자 값 받기
        String puTel = tf_puTel.getText();
        String puManager = tf_puManager.getText();
        String puHp = tf_puHp.getText();

        // + 유효성 검사
        if (puTel == null || puTel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "회사 번호를 입력하세요.");
            tf_puTel.requestFocus();
            return;
        } else if (puManager == null || puManager.isEmpty()) {
            JOptionPane.showMessageDialog(this, "담당자 이름을 입력하세요.");
            tf_puManager.requestFocus();
            return;
        } else if (puHp == null || puHp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "담당자 번호를 입력하세요.");
            tf_puHp.requestFocus();
            return;
        }

        //2. sql 로직 처리하기
        PublisherDTO dto = new PublisherDTO(puId, puHp, puTel, puManager, puHp);
        
        dto.setPuTel(puTel);
        dto.setPuManager(puManager);
        dto.setPuHp(puHp);
        
        int result = Dao.editPu(dto);
        
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "수정이 완료되었습니다.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "수정에 실패하였습니다.");
            return;
        }

    }
    
    //저장된 정보 출력
    public void showPublisher() throws SQLException {
        //1 
        //2 호출
        PublisherDTO dto = Dao.Editshowdata(puId);
        
        //3 값 출력
        String puid = dto.getPuId();
        String puname = dto.getPuName();
        String putel = dto.getPuTel();
        String pumanager = dto.getPuManager();
        String puhp = dto.getPuHp();
        
        tf_puId.setText(dto.getPuTel());
        tf_puName.setText(dto.getPuName());
        tf_puTel.setText(dto.getPuTel());
        tf_puManager.setText(dto.getPuManager());
        tf_puHp.setText(dto.getPuHp());
        
    }//showPublisher

}
