/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.SaleAddDAO;
import model.SaleAddDTO;

/**
 *
 * @author yj
 */
public class SaleAdd extends javax.swing.JFrame implements ActionListener{
    private SaleAddDAO addDao;
    /**
     * Creates new form SaleAdd
     */
    public SaleAdd() {
        initComponents();
        init();
        addEvent();
        setLocationRelativeTo(null); //가운데 배치
    }

    private void init() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        try {
            setSellNo();
            getSubjectList();
            getIdList();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        tf_sellNo.setEditable(false);
        tf_sellNo.setBackground(Color.LIGHT_GRAY);

    }

    //이벤트 처리
    private void addEvent() {
        bt_ok.addActionListener(this);

    }

    //======================================이벤트 핸들러=====================================================

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == bt_ok) {
            try {
                //확인버튼 클릭시
                insertSell();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_sellNo = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_subject = new javax.swing.JLabel();
        lb_qty = new javax.swing.JLabel();
        bt_ok = new javax.swing.JButton();
        tf_sellNo = new javax.swing.JTextField();
        cb_id = new javax.swing.JComboBox<>();
        cb_subject = new javax.swing.JComboBox<>();
        tf_qty = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(450, 300));

        lb_sellNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_sellNo.setText("판매번호");

        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_id.setText("아이디");

        lb_subject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_subject.setText("구매상품");

        lb_qty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_qty.setText("판매수량");

        bt_ok.setText("등록");

        cb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_qty)
                        .addGap(18, 18, 18)
                        .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_sellNo)
                        .addGap(18, 18, 18)
                        .addComponent(tf_sellNo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_subject)
                        .addGap(18, 18, 18)
                        .addComponent(cb_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(bt_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_sellNo)
                    .addComponent(tf_sellNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_id)
                    .addComponent(cb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_subject)
                    .addComponent(cb_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_qty)
                    .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bt_ok)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ok;
    private javax.swing.JComboBox<String> cb_id;
    private javax.swing.JComboBox<String> cb_subject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_qty;
    private javax.swing.JLabel lb_sellNo;
    private javax.swing.JLabel lb_subject;
    private javax.swing.JTextField tf_qty;
    private javax.swing.JTextField tf_sellNo;
    // End of variables declaration//GEN-END:variables
    private void setSellNo() throws SQLException { //판매번호 자동화
        addDao = new SaleAddDAO(); 
        SaleAddDTO dto = addDao.AddSellNo(); //판매번호DTO 생성
        tf_sellNo.setText(dto.getSellNo()); // DTO담긴 SellNo를 텍스쳐필드에 setText
       
    }

    private void getSubjectList() throws SQLException {//book테이블 DB값 받아와서 콤보박스에 넣기

        Vector<String> vec=addDao.getBookInfo();
        DefaultComboBoxModel<String> cbModel = new DefaultComboBoxModel<>(vec);
        cb_subject.setModel(cbModel);
    }

    private void getIdList() throws SQLException { //member테이블 DB값 받아와서 콤보박스에 넣기
        Vector<String> vec=addDao.getIdInfo();
        DefaultComboBoxModel<String> cbModel = new DefaultComboBoxModel<>(vec);
        cb_id.setModel(cbModel);
    }

    private void insertSell() throws SQLException { //판매DB입력
        
        String sellNo=tf_sellNo.getText(); //판매번호
        String id=cb_id.getSelectedItem().toString(); //아이디
        String subject=cb_subject.getSelectedItem().toString(); //책 제목
        String str=tf_qty.getText();//수량
        if(str.isEmpty() || str==null){ //유효성 검사
            JOptionPane.showMessageDialog(this, "수량을 입력해주세요.");
            tf_qty.requestFocus();
            return;
        }
        int qty = Integer.parseInt(str); // 구매할 수량
        
        SaleAddDTO book=addDao.getBookInfo(subject); //책 제목으로 해당 책의 가격,책번호 받아오기
        int bookNo=book.getBookNo(); //책 번호
        
        SaleAddDTO dto1=addDao.checkStock(bookNo); // 해당 책번호
        int stock = dto1.getQty(); // 구매할 개수로
        if(qty>stock){ // 재고확인후 부족하다면 재고 부족 팝업후 창닫기
            JOptionPane.showMessageDialog(this, "재고가 부족합니다 해당책의 현재 재고는 "+stock+"개 입니다.");
            this.dispose();
            return;        
        }
        //재고가 구매수량보다 적다면 진행
        SaleAddDTO dto = new SaleAddDTO(sellNo, id);
        int result1 = addDao.insertSell(dto); //판매테이블 DB값 저장
        
        dto = new SaleAddDTO(bookNo, qty, sellNo);//해당 책번호, 수량받아서
        int result2 = addDao.insertSellItem(dto); //판매아이템 테이블 DB값 저장
        
        if(result1==1 && result2==1){ //결과 팝업창
            this.dispose();
            JOptionPane.showMessageDialog(this, "판매등록에 성공했습니다.");
            //해당 책번호, 수량받아서
            addDao.minusStock(dto); //해당재고 -수량 처리
            
        }else JOptionPane.showMessageDialog(this, "판매등록에 실패하였습니다.");
        
    }
}
